const OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast";

const WMO_CONDITIONS = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Drizzle: light",
  53: "Drizzle: moderate",
  55: "Drizzle: dense",
  56: "Freezing drizzle: light",
  57: "Freezing drizzle: dense",
  61: "Rain: slight",
  63: "Rain: moderate",
  65: "Rain: heavy",
  66: "Freezing rain: light",
  67: "Freezing rain: heavy",
  71: "Snow fall: slight",
  73: "Snow fall: moderate",
  75: "Snow fall: heavy",
  77: "Snow grains",
  80: "Rain showers: slight",
  81: "Rain showers: moderate",
  82: "Rain showers: violent",
  85: "Snow showers: slight",
  86: "Snow showers: heavy",
  95: "Thunderstorm: slight or moderate",
  96: "Thunderstorm with slight hail",
  99: "Thunderstorm with heavy hail",
};

const WMO_HINTS = {
  0: "Perfect for outdoor fun",
  1: "Shades recommended",
  2: "A light jacket might be smart",
  3: "Cozy indoor activities sound nice",
  45: "Visibility is low — take it slow",
  48: "Slippery surfaces possible",
  51: "You’ll feel a few drops",
  53: "Keep a hood handy",
  55: "You’ll get damp quickly",
  56: "Watch your step — it can freeze",
  57: "High slipping risk",
  61: "Bring an umbrella",
  63: "Raincoat time",
  65: "Outdoor plans in danger",
  66: "Ice on everything — be careful",
  67: "Roads can become ice rinks",
  71: "Winter vibes incoming",
  73: "Snowball potential",
  75: "Stay warm — very snowy",
  77: "Icy sprinkles — unusual day",
  80: "Short wet surprises",
  81: "Expect sudden soaking moments",
  82: "Find shelter fast",
  85: "Light flakes — pretty views",
  86: "Slippery chaos possible",
  95: "Better stay close to buildings",
  96: "Watch out for falling ice pellets",
  99: "Stay inside — danger from above",
};

const COORDINATES = {
  kyiv: [50.450001, 30.523333],
  barcelona: [41.390205, 2.154007],
  london: [51.507351, -0.117758],
  dubai: [25.276987, 55.296249],
  oslo: [59.913868, 10.752245],
};

module.exports = {
  WMO_CONDITIONS,
  OPEN_METEO_URL,
  WMO_HINTS,
  COORDINATES,
};
